### ISSUE TITLE
Makefile:13: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by mrr1vfe** [casouri/lunarymacs#16]
Unable to run make inside ~/.emacs.d
Error message is "Makefile:13: *** missing separator.  Stop."

I tried to open the Emacs with this error, and Emacs is telling me that "file-missing"

I am running Emacs version 26.1 on macOS 10.14.2

**Comment by casouri** [comment]
You need a new version of Make. The default one in Mac is too old.

**Comment by mrr1vfe** [comment]
Thank you for your response.
I have updated make from version 3 to version 4.2.1
I ran make, and this is what I got:

mkdir .local .local/package .local/package/elpa
touch .local/custom.el
touch .local/autoload.el
Symbol's value as variable is void: user-emacs-directory
make: *** [Makefile:13: all] Error 255

**Comment by mrr1vfe** [comment]
It turns out that the Emacs comes with my macOS is also not-up-to-date.
After I updated Emacs from 22 to 26, make works fine.
