### ISSUE TITLE
能不能对luna-load-package.el相对use-package进行一个大致的比较

### ISSUE THREAD

**Issue by QiangF** [casouri/lunarymacs#19]
你的配置好独特，对这两个的比较对刚学会配置emacs非常有帮助。谢谢！

**Comment by casouri** [comment]
啊，没有什么深层的区别。`luna-load-package`的实现更简单直接，代码量也小，功能则比`use-package`少很多（功能重叠的部份没啥区别）。好处是我可以随便改。而且用`use-package`的话整个配置都要依赖一个第三方包，有点奇怪。

初学emacs配置的话还是用`use-package`吧，自己写只是我的任性www
