### ISSUE TITLE
iscroll-mode导致行之间移动时，光标列位置偏移很多（中文内容）

### ISSUE THREAD

**Issue by ringawho** [casouri/lunarymacs#21]
开启`iscroll-mode`之后，如果`org`文件中的内容是中文，就会出现这种问题，比如现在第一行第15个字符，光标向下移动一行，就到了第8个字符，关闭`iscroll-mode`就会正常

**Comment by casouri** [comment]
Should be fixed now. Thanks.

**Comment by ringawho** [comment]
我又来了，应该是因为我开了折行（`truncate-lines`），现在折行的地方出现错了。比如一行折成了三行，如果光标在第三行，那么光标向上移动一行，就会到第三行开头。另外如果光标是一行一行移下去，那么向上移动就是正常的

**Comment by casouri** [comment]
虽然我没太看懂，不过确实column还是有个问题。现在修复了，不知道我修复的是不是你描述的问题。

**Comment by casouri** [comment]
另外你是不是想说word-wrap？truncate-line的效果是不折行。

**Comment by ringawho** [comment]
刚刚试了一下，应该没问题了

我也不太清楚这个，我是设置了`(setq-local truncate-lines nil)`，这样就会折行，其它的没有设置

麻烦你啦
