### ISSUE TITLE
[FR] evil support for `luna-key`

### ISSUE THREAD

**Issue by bangedorrunt** [casouri/lunarymacs#24]
@casouri, I'm wondering if you could make evil support for your custom keybinding just like `general.el`?

**Comment by casouri** [comment]
I don't really know about evil. I wonder why do you not want to use general.el? After all, luna-key.el is tied to my config and not for general use, unlike general.el.

**Comment by casouri** [comment]
Thanks, that's an interesting read. I guess that's the fate of trying to make something solve everything ;-)
