### ISSUE TITLE
consider moving `expreg.el` to it's own repo

### ISSUE THREAD

**Issue by waymondo** [casouri/lunarymacs#25]
I'm finding `expreg.el` to work quite well and would like to try replacing `expand-region` / `puni` with it in my .emacs. Would you consider moving it into it's own repo? If you aren't ready to publish it to MELPA / ELPA, etc, just having it in its own repo would still make it easy to install in isolation with `package-vc` or `straight`. It would also allow the project to start receiving contributions.

P.S. Thanks for all your work surrounding treesit in Emacs core!

**Comment by casouri** [comment]
Thanks for your kind words! I'm glad you find it useful. I moved it to https://github.com/casouri/expreg.
